// course-reference.ts — recorded reference runs for the fixed courses.
//
// These are NOT human records and NOT invented targets. Each payload is an
// actual clean simulated completion (0 respawns, 0 wall contacts) of the exact
// authored course, captured with the skilled controller and encoded by the
// shared ghost codec with a packed course identity. `reference` is surfaced to
// the UI as REFERENCE, never as a best/human/world record.
//
// Provenance (deterministic, reproducible by the courses test): course-retune
// recordings on the current physics (ACCEL_ROAD 85 + ACCEL_BOOST_MAKEUP 55 +
// LAUNCH_RAMP_MIN 0.15 rising to full by LAUNCH_RAMP_END 80, slides and rail
// contact bypassing the ramp, cruise 140 / drift 112, gated rail clamp,
// terminal road-relative dirt (ACCEL_OFFROAD 6 / OFFROAD_DRAG 1.0),
// gate-free ground station).
// Each payload is the exact skilled-controller run the C5 check replays
// (0 walls, 0 respawns).
//   practice  (2026-01-01) clean informed run, 9899 ms, tag practice.
//   benchmark (2026-01-02) clean informed run, 16685 ms, tag benchmark.
// Re-recorded 2026-09-18 (sink2): the decisive launch softening retimed the
// skilled runs (+366/+417 ms, launch + slow-corner pull); geometry checksums
// unchanged (practice 29e9fc3b, benchmark 1ecc1323).
// Re-recorded 2026-09-18 (feel3): the third slow-launch report deepened the
// ramp (0.35/60 -> 0.15/80, ACCEL_ROAD untouched) and made dirt terminal,
// retiming the skilled runs (+359/+596 ms, launch + slow-corner pull);
// geometry checksums unchanged (practice 29e9fc3b, benchmark 1ecc1323).
// The encoded payload carries { day, courseChecksum, gen }; course.ts checks it
// against the freshly built geometry before handing it out.
import { TRACK_IDENTITY_GEN } from './ghost.js';

// Bumped for the speed-dirt pass: geometry, physics pace and competition
// identity changed, so medal margins and reference recordings must be
// re-derived. See docs/agents/speed-dirt-courses.md.
export const COURSE_REFERENCE_VERSION = 2;

/**
 * Encoding budget for the bundled reference demos. These are shipped locally
 * with the build, not share URLs, so they are encoded at effectively unlimited
 * budget to keep EVERY 120 ms recorded sample. Using the share-URL budget
 * (GHOST_URL_BUDGET) strides the demo roughly 1s apart and interpolation then
 * cuts up to ~3u through inside curbs; the full payloads stay under the codec's
 * 8192-char decode limit and interpolate within the 0.5u quantization bound.
 */
export const REFERENCE_ENCODE_BUDGET = 1 << 30;

/** Encoded GhostRec payloads (base64url, versioned codec with course identity). */
export const REFERENCE_ENCODED: Record<'practice' | 'benchmark', string> = {
  practice:
    'eyJ2IjozLCJ0Ijo5ODk5LCJwIjpbWzAsNiwwLDBdLFswLDYsMS41LDBdLFswLDYsMy41LDBdLFswLDYsNiwwXSxbMCw2LDksMF0sWzAsNiwxMywwXSxbMCw2LDE3LDBdLFswLDYsMjIuNSwwXSxbMCw2LDI4LjUsMF0sWzAsNiwzNS41LDBdLFswLDYsNDMuNSwwXSxbMCw2LDUzLDBdLFswLDYsNjQsMF0sWzAsNiw3Ni41LDBdLFswLDYsOTAuNSwwXSxbMCw2LDEwNiwwXSxbMCw2LDEyMi41LC0wLjAyXSxbLTAuNSw2LDEzOS41LC0wLjA4XSxbLTEuNSw2LDE1NS41LC0wLjE3XSxbLTMsNiwxNzAuNSwtMC4yNl0sWy02LDYsMTg1LjUsLTAuMzhdLFstMTAuNSw2LDE5OS41LC0wLjUxXSxbLTE2LjUsNiwyMTMuNSwtMC42Nl0sWy0yNCw2LDIyNi41LC0wLjgzXSxbLTM0LDYsMjM4LC0xLjA0XSxbLTQ2LDYuNSwyNDgsLTEuMjRdLFstNTkuNSw3LjUsMjU1LjUsLTEuNDFdLFstNzQsOCwyNjAuNSwtMS41NV0sWy04OSw4LDI2MywtMS42N10sWy0xMDQsOC41LDI2My41LC0xLjc1XSxbLTExOSw4LjUsMjYyLjUsLTEuOF0sWy0xMzQuNSw4LjUsMjYwLC0xLjgzXSxbLTE1MC41LDguNSwyNTYsLTIuMDFdLFstMTY2LjUsOC41LDI1MC41LC0yLjAyXSxbLTE4Mi41LDguNSwyNDMuNSwtMS45NV0sWy0yMDAuNSw4LjUsMjM2LjUsLTEuODhdLFstMjE5LjUsOC41LDIyOS41LC0xLjY4XSxbLTI0MCw5LDIyNC41LC0xLjUyXSxbLTI2MS41LDEwLDIyMi41LC0xLjM4XSxbLTI4MSwxMC41LDIyMi41LC0xLjMxXSxbLTI5OSwxMS41LDIyNC41LC0xLjI5XSxbLTMxNS41LDEyLDIyNywtMS4yMV0sWy0zMzAsMTIsMjMxLC0xLjA2XSxbLTM0NCwxMi41LDIzNi41LC0wLjgyXSxbLTM1Ni41LDEyLjUsMjQ0LC0wLjU5XSxbLTM2NywxMi41LDI1My41LC0wLjQxXSxbLTM3NSwxMi41LDI2NCwtMC4yN10sWy0zODEuNSwxMi41LDI3NiwtMC4xNl0sWy0zODYsMTIuNSwyODgsLTAuMDZdLFstMzg5LDEyLjUsMzAxLDAuMDJdLFstMzkwLjUsMTIuNSwzMTQuNSwwLjA3XSxbLTM5MSwxMi41LDMyOCwwLjEyXSxbLTM5MC41LDEzLDM0MS41LDAuMTZdLFstMzg5LDEzLjUsMzU1LjUsMC4xOF0sWy0zODcsMTQsMzY5LjUsMC4xOF0sWy0zODUsMTQuNSwzODQsMC4xNl0sWy0zODMsMTQuNSwzOTgsMC4xNV0sWy0zODEsMTQuNSw0MTIuNSwwLjEzXSxbLTM3OSwxMy41LDQyNi41LDAuMV0sWy0zNzcsMTIuNSw0NDAuNSwwLjA3XSxbLTM3NSwxMS41LDQ1NSwwLjAyXSxbLTM3NCwxMSw0NzEsLTAuMDVdLFstMzc0LjUsMTAsNDg5LC0wLjE5XSxbLTM3Ny41LDguNSw1MDgsLTAuMzNdLFstMzgyLjUsOCw1MjcuNSwtMC40NV0sWy0zOTAsNy41LDU0OCwtMC41NF0sWy0zOTguNSw3LDU2Ni41LC0wLjYxXSxbLTQwOC41LDcsNTgzLC0wLjYyXSxbLTQxOC41LDcsNTk4LjUsLTAuNjVdLFstNDI5LjUsNyw2MTMuNSwtMC42OV0sWy00NDEuNSw3LDYyOC41LC0wLjcxXSxbLTQ1My41LDcsNjQyLjUsLTAuNzNdLFstNDY1LjUsNyw2NTYuNSwtMC43NF0sWy00NzguNSw3LDY3MC41LC0wLjc1XSxbLTQ5MSw3LDY4NCwtMC43OF0sWy00OTQsNyw2ODcuNSwtMC44XV0sInRzIjpbMCwxMzMsMjY3LDQwMCw1MzMsNjY3LDgwMCw5MzMsMTA2NywxMjAwLDEzMzMsMTQ2NywxNjAwLDE3MzMsMTg2NywyMDAwLDIxMzMsMjI2NywyNDAwLDI1MzMsMjY2NywyODAwLDI5MzMsMzA2NywzMjAwLDMzMzMsMzQ2NywzNjAwLDM3MzMsMzg2Nyw0MDAwLDQxMzMsNDI2Nyw0NDAwLDQ1MzMsNDY2Nyw0ODAwLDQ5MzMsNTA2Nyw1MjAwLDUzMzMsNTQ2Nyw1NjAwLDU3MzMsNTg2Nyw2MDAwLDYxMzMsNjI2Nyw2NDAwLDY1MzMsNjY2Nyw2ODAwLDY5MzMsNzA2Nyw3MjAwLDczMzMsNzQ2Nyw3NjAwLDc3MzMsNzg2Nyw4MDAwLDgxMzMsODI2Nyw4NDAwLDg1MzMsODY2Nyw4ODAwLDg5MzMsOTA2Nyw5MjAwLDkzMzMsOTQ2Nyw5NjAwLDk3MzMsOTg2Nyw5ODk5XSwidHJhY2siOnsiZGF5IjoiMjAyNi0wMS0wMSIsImNvdXJzZSI6IjI5ZTlmYzNiIiwiZ2VuIjoyfX0',
  benchmark:
    'eyJ2IjozLCJ0IjoxNjY4NSwicCI6W1swLDYsMCwwXSxbMCw2LDEuNSwwXSxbMCw2LDMuNSwwXSxbMCw2LDYsMF0sWzAsNiw5LDBdLFswLDYsMTMsMF0sWzAsNiwxNywwXSxbMCw2LDIyLjUsMF0sWzAsNiwyOC41LDBdLFswLDYsMzUuNSwwXSxbMCw2LDQzLjUsMF0sWzAsNiw1MywwXSxbMCw2LDY0LDBdLFswLDYsNzYuNSwwXSxbMCw2LDkwLjUsMF0sWzAsNiwxMDYsMF0sWzAsNiwxMjMsMC4wMV0sWzAsNiwxNDAuNSwwLjA0XSxbMSw2LDE1OCwwLjExXSxbMiw2LDE3NC41LDAuMl0sWzQuNSw2LDE5MCwwLjNdLFs4LDYsMjA1LDAuNDFdLFsxMi41LDYsMjE5LDAuNTRdLFsxOSw2LDIzMywwLjY3XSxbMjcsNi41LDI0NS41LDAuODNdLFszNyw2LjUsMjU3LDEuMDFdLFs0OC41LDcsMjY3LDEuMTldLFs2Miw3LjUsMjc0LjUsMS4zN10sWzc2LDcuNSwyODAsMS41M10sWzkxLDcuNSwyODMuNSwxLjY2XSxbMTA2LjUsNy41LDI4NCwxLjc3XSxbMTIxLjUsNy41LDI4My41LDEuODVdLFsxMzYsNywyODEsMS45MV0sWzE1MC41LDcsMjc3LDEuOTRdLFsxNjUsNi41LDI3MiwyLjEyXSxbMTc4LjUsNi41LDI2NS41LDIuMTJdLFsxOTMsNi41LDI1Ny41LDIuMDRdLFsyMDksNywyNDkuNSwxLjk1XSxbMjI2LjUsNywyNDEuNSwxLjczXSxbMjQ1LDcuNSwyMzUuNSwxLjU0XSxbMjY0LjUsOCwyMzIuNSwxLjM5XSxbMjgzLDguNSwyMzIsMS4zMV0sWzI5OS41LDksMjMzLDEuMjZdLFszMTQuNSw5LDIzNS41LDEuMTVdLFszMjksOSwyNDAsMC45NV0sWzM0Mi41LDksMjQ2LDAuNzNdLFszNTQsOSwyNTQsMC41NF0sWzM2My41LDksMjY0LDAuMzddLFszNzEsOC41LDI3NSwwLjI1XSxbMzc3LDguNSwyODcsMC4xNF0sWzM4MSw4LjUsMjk5LDAuMDVdLFszODMuNSw4LjUsMzEyLC0wLjAyXSxbMzg1LDguNSwzMjUuNSwtMC4wOF0sWzM4NSw4LjUsMzM5LC0wLjEyXSxbMzg0LjUsOS41LDM1Mi41LC0wLjE1XSxbMzgzLjUsMTEuNSwzNjYuNSwtMC4xN10sWzM4MiwxMi41LDM4MC41LC0wLjE3XSxbMzgwLjUsMTIuNSwzOTQuNSwtMC4xN10sWzM3OSwxMiw0MDksLTAuMTZdLFszNzcuNSwxMS41LDQyMywtMC4xNl0sWzM3NiwxMC41LDQzNywtMC4xNV0sWzM3NCwxMSw0NTEsLTAuMTRdLFszNzIsMTEsNDY2LC0wLjEzXSxbMzcwLDExLDQ4MC41LC0wLjEyXSxbMzY4LjUsMTEsNDk1LjUsLTAuMTFdLFszNjYuNSwxMSw1MTAsLTAuMDldLFszNjUsMTAuNSw1MjUsLTAuMDddLFszNjQsMTAuNSw1MzkuNSwtMC4wNF0sWzM2MywxMC41LDU1NC41LDBdLFszNjIuNSwxMCw1NjkuNSwwLjA2XSxbMzYzLDEwLDU4NCwwLjEzXSxbMzY0LDEwLjUsNTk5LDAuMl0sWzM2NiwxMC41LDYxNCwwLjI5XSxbMzY5LDEwLjUsNjI4LjUsMC4zN10sWzM3My41LDExLDY0Mi41LDAuNDRdLFszNzksMTEuNSw2NTYuNSwwLjUxXSxbMzg1LDEyLDY3MCwwLjU2XSxbMzkyLDEyLDY4My41LDAuNl0sWzQwMC41LDEyLjUsNjk2LjUsMC42M10sWzQxMSwxMi41LDcxMS41LDAuNjNdLFs0MjEuNSwxMi41LDcyNi41LDAuNjFdLFs0MzIsMTIuNSw3NDEuNSwwLjU0XSxbNDQxLjUsMTIuNSw3NTYuNSwwLjQxXSxbNDQ5LDEyLDc3MS41LDAuMjddLFs0NTUsMTIsNzg1LjUsMC4xNl0sWzQ1OSwxMiw3OTcsMC4wOF0sWzQ2MiwxMiw4MDYuNSwtMC4wMl0sWzQ2My41LDEyLDgxNiwtMC4zMV0sWzQ2Mi41LDEyLDgyNiwtMC42MV0sWzQ1OSwxMiw4MzUsLTAuODNdLFs0NTMuNSwxMi41LDg0My41LC0wLjkxXSxbNDQ2LDEyLjUsODUxLjUsLTAuOTJdLFs0MzcuNSwxMyw4NTkuNSwtMC45M10sWzQyNy41LDEzLjUsODY3LC0wLjk5XSxbNDE3LDEzLjUsODc1LC0xLjA2XSxbNDA1LjUsMTQsODgyLC0xLjEzXSxbMzkzLDE0LDg4OSwtMS4xNV0sWzM3OS41LDE0LjUsODk2LC0xLjE1XSxbMzY2LDE0LjUsOTAyLC0xLjE0XSxbMzUzLDE0LjUsOTA4LjUsLTEuMTNdLFszMzkuNSwxNC41LDkxNSwtMS4xM10sWzMyNiwxNCw5MjEsLTEuMTNdLFszMTIuNSwxNCw5MjcuNSwtMS4xM10sWzI5OSwxNCw5MzMuNSwtMS4xMV0sWzI4NiwxNCw5NDAsLTEuMDddLFsyNzIuNSwxMy41LDk0NywtMS4wMl0sWzI2MCwxMyw5NTQuNSwtMC45N10sWzI0NywxMi41LDk2MiwtMC45XSxbMjM1LDEyLDk3MC41LC0wLjgzXSxbMjIzLjUsMTEuNSw5ODAsLTAuNzVdLFsyMTIuNSwxMC41LDk5MCwtMC42N10sWzIwMiwxMCwxMDAwLjUsLTAuNTldLFsxOTIuNSw5LDEwMTIsLTAuNTNdLFsxODQsOC41LDEwMjQuNSwtMC40OF0sWzE3Niw4LDEwMzcsLTAuNDZdLFsxNjksNy41LDEwNTAsLTAuNDRdLFsxNjIsNywxMDYzLC0wLjQxXSxbMTU1LjUsNywxMDc2LC0wLjM4XSxbMTQ5LjUsNywxMDkwLjUsLTAuMzZdLFsxNDMsNywxMTA3LC0wLjM1XSxbMTM2LjUsNywxMTI0LjUsLTAuMzVdLFsxMzAsNywxMTQyLC0wLjM2XSxbMTIzLjUsNywxMTU5LjUsLTAuMzZdLFsxMTcsNywxMTc3LC0wLjM2XSxbMTEwLjUsNywxMTk0LjUsLTAuMzZdLFsxMDMuNSw3LDEyMTIsLTAuMzddLFsxMDMsNywxMjE0LjUsLTAuMzddXSwidHMiOlswLDEzMywyNjcsNDAwLDUzMyw2NjcsODAwLDkzMywxMDY3LDEyMDAsMTMzMywxNDY3LDE2MDAsMTczMywxODY3LDIwMDAsMjEzMywyMjY3LDI0MDAsMjUzMywyNjY3LDI4MDAsMjkzMywzMDY3LDMyMDAsMzMzMywzNDY3LDM2MDAsMzczMywzODY3LDQwMDAsNDEzMyw0MjY3LDQ0MDAsNDUzMyw0NjY3LDQ4MDAsNDkzMyw1MDY3LDUyMDAsNTMzMyw1NDY3LDU2MDAsNTczMyw1ODY3LDYwMDAsNjEzMyw2MjY3LDY0MDAsNjUzMyw2NjY3LDY4MDAsNjkzMyw3MDY3LDcyMDAsNzMzMyw3NDY3LDc2MDAsNzczMyw3ODY3LDgwMDAsODEzMyw4MjY3LDg0MDAsODUzMyw4NjY3LDg4MDAsODkzMyw5MDY3LDkyMDAsOTMzMyw5NDY3LDk2MDAsOTczMyw5ODY3LDEwMDAwLDEwMTMzLDEwMjY3LDEwNDAwLDEwNTMzLDEwNjY3LDEwODAwLDEwOTMzLDExMDY3LDExMjAwLDExMzMzLDExNDY3LDExNjAwLDExNzMzLDExODY3LDEyMDAwLDEyMTMzLDEyMjY3LDEyNDAwLDEyNTMzLDEyNjY3LDEyODAwLDEyOTMzLDEzMDY3LDEzMjAwLDEzMzMzLDEzNDY3LDEzNjAwLDEzNzMzLDEzODY3LDE0MDAwLDE0MTMzLDE0MjY3LDE0NDAwLDE0NTMzLDE0NjY3LDE0ODAwLDE0OTMzLDE1MDY3LDE1MjAwLDE1MzMzLDE1NDY3LDE1NjAwLDE1NzMzLDE1ODY3LDE2MDAwLDE2MTMzLDE2MjY3LDE2NDAwLDE2NTMzLDE2NjY3LDE2Njg1XSwidHJhY2siOnsiZGF5IjoiMjAyNi0wMS0wMiIsImNvdXJzZSI6IjFlY2MxMzIzIiwiZ2VuIjoyfX0',
};

/** Fixed-course identity days (daily keeps the requested day). */
export const FIXED_IDENTITY_DAYS: Record<'practice' | 'benchmark', string> = {
  practice: '2026-01-01',
  benchmark: '2026-01-02',
};

/** Recorded exact finish times (ms) of the reference runs, for documentation. */
export const REFERENCE_TIMES_MS: Record<'practice' | 'benchmark', number> = {
  practice: 9899,
  benchmark: 16685,
};

/**
 * Medal margins over the recorded reference time. Gold is deliberately slower
 * than the reference (which was a clean skilled run), so gold is attainable
 * while the REFERENCE stays the pace to chase.
 */
export const FIXED_TARGET_MARGINS = { gold: 1.08, silver: 1.2, bronze: 1.36 } as const;

/**
 * Daily medal factors over `estimateCleanTime`. Calibrated offline against 22
 * representative daily seeds driven by the skilled controller: clean-run
 * time/estimate ratios were 1.031-1.054 (median 1.045). Gold at 1.10 keeps a
 * ~5% margin over that measured clean pace; silver/bronze step out for a wider
 * player base.
 */
export const DAILY_TARGET_FACTORS = { gold: 1.1, silver: 1.22, bronze: 1.4 } as const;

export const COURSE_IDENTITY_GEN = TRACK_IDENTITY_GEN;
