// course-reference.ts — recorded reference runs for the fixed courses.
//
// These are NOT human records and NOT invented targets. Each payload is an
// actual clean simulated completion (0 respawns, 0 wall contacts) of the exact
// authored course, captured with the skilled controller and encoded by the
// shared ghost codec with a packed course identity. `reference` is surfaced to
// the UI as REFERENCE, never as a best/human/world record.
//
// Provenance (deterministic, reproducible by the courses test): course-retune
// recordings on the current physics (ACCEL_ROAD 110 + ACCEL_BOOST_MAKEUP 30,
// cruise 140 / drift 112, gated rail clamp). Each payload is the exact
// skilled-controller run the C5 check replays (0 walls, 0 respawns).
//   practice  (2026-01-01) clean informed run, 9075 ms, tag practice.
//   benchmark (2026-01-02) clean informed run, 15488 ms, tag benchmark.
// The encoded payload carries { day, courseChecksum, gen }; course.ts checks it
// against the freshly built geometry before handing it out.
import { TRACK_IDENTITY_GEN } from './ghost.js';

// Bumped for the speed-dirt pass: geometry, physics pace and competition
// identity changed, so medal margins and reference recordings must be
// re-derived. See docs/agents/speed-dirt-courses.md.
export const COURSE_REFERENCE_VERSION = 2;

/**
 * Encoding budget for the bundled reference demos. These are shipped locally
 * with the build, not share URLs, so they are encoded at effectively unlimited
 * budget to keep EVERY 120 ms recorded sample. Using the share-URL budget
 * (GHOST_URL_BUDGET) strides the demo roughly 1s apart and interpolation then
 * cuts up to ~3u through inside curbs; the full payloads stay under the codec's
 * 8192-char decode limit and interpolate within the 0.5u quantization bound.
 */
export const REFERENCE_ENCODE_BUDGET = 1 << 30;

/** Encoded GhostRec payloads (base64url, versioned codec with course identity). */
export const REFERENCE_ENCODED: Record<'practice' | 'benchmark', string> = {
  practice:
    'eyJ2IjozLCJ0Ijo5MDc1LCJwIjpbWzAsNiwwLDBdLFswLDYsMi41LDBdLFswLDYsNywwXSxbMCw2LDEzLDBdLFswLDYsMjEuNSwwXSxbMCw2LDMxLjUsMF0sWzAsNiw0NCwwXSxbMCw2LDU4LDBdLFswLDYsNzQsMF0sWzAsNiw5Mi41LDBdLFswLDYsMTExLC0wLjAyXSxbLTAuNSw2LDEyOSwtMC4wNl0sWy0xLjUsNiwxNDYuNSwtMC4xNF0sWy0zLDYsMTYzLjUsLTAuMjNdLFstNS41LDYsMTc5LC0wLjM0XSxbLTkuNSw2LDE5NCwtMC40Nl0sWy0xNC41LDYsMjA4LC0wLjU4XSxbLTIxLjUsNiwyMjEsLTAuNzNdLFstMzAuNSw2LDIzMy41LC0wLjkzXSxbLTQxLjUsNi41LDI0NC41LC0xLjE1XSxbLTU0LDcsMjUzLC0xLjM0XSxbLTY4LDcuNSwyNTksLTEuNV0sWy04Myw4LDI2MywtMS42M10sWy05OCw4LDI2NC41LC0xLjczXSxbLTExMyw4LjUsMjY0LC0xLjc5XSxbLTEyOCw4LjUsMjYyLC0xLjgzXSxbLTE0NC41LDguNSwyNTgsLTEuOThdLFstMTYwLDguNSwyNTMsLTIuMDZdLFstMTc2LDguNSwyNDYuNSwtMS45OF0sWy0xOTMsOC41LDIzOSwtMS45MV0sWy0yMTIsOC41LDIzMiwtMS43Ml0sWy0yMzEuNSw5LDIyNiwtMS41OF0sWy0yNTMsOS41LDIyMi41LC0xLjQzXSxbLTI3My41LDEwLDIyMiwtMS4zM10sWy0yOTIsMTEsMjIzLC0xLjNdLFstMzA4LjUsMTEuNSwyMjUuNSwtMS4yNV0sWy0zMjQsMTIsMjI5LC0xLjEzXSxbLTMzOC41LDEyLjUsMjM0LC0wLjkyXSxbLTM1MiwxMi41LDI0MSwtMC42N10sWy0zNjMuNSwxMi41LDI1MC41LC0wLjQ2XSxbLTM3My41LDEyLjUsMjYxLjUsLTAuM10sWy0zODEsMTIuNSwyNzQuNSwtMC4xOF0sWy0zODYsMTIuNSwyODgsLTAuMDddLFstMzg5LjUsMTIuNSwzMDMsMC4wMV0sWy0zOTEuNSwxMi41LDMxOCwwLjA4XSxbLTM5Mi41LDEzLDMzMi41LDAuMTVdLFstMzkxLjUsMTMsMzQ3LjUsMC4yMV0sWy0zOTAsMTMuNSwzNjIuNSwwLjIzXSxbLTM4Ny41LDE0LDM3NywwLjIzXSxbLTM4NSwxNC41LDM5MS41LDAuMjFdLFstMzgyLjUsMTQuNSw0MDYsMC4xOF0sWy0zODAsMTQsNDIxLDAuMTVdLFstMzc3LjUsMTMsNDM1LjUsMC4xXSxbLTM3NSwxMS41LDQ1MCwwLjA1XSxbLTM3My41LDExLDQ2NS41LC0wLjAxXSxbLTM3MywxMC41LDQ4MSwtMC4wOF0sWy0zNzQuNSw5LjUsNDk4LC0wLjJdLFstMzc3LjUsOC41LDUxNiwtMC4zNl0sWy0zODMsNy41LDUzNS41LC0wLjQ4XSxbLTM5MC41LDcuNSw1NTQuNSwtMC41N10sWy0zOTkuNSw3LDU3MS41LC0wLjYzXSxbLTQwOSw3LDU4NywtMC42Nl0sWy00MTkuNSw3LDYwMi41LC0wLjY5XSxbLTQzMS41LDcsNjE3LC0wLjcyXSxbLTQ0My41LDcsNjMxLC0wLjc0XSxbLTQ1Niw3LDY0NSwtMC43NV0sWy00NjksNyw2NTguNSwtMC43NV0sWy00ODEuNSw3LDY3MiwtMC43Nl0sWy00OTQuNSw3LDY4NS41LC0wLjc3XSxbLTQ5NSw3LDY4Ni41LC0wLjc3XV0sInRzIjpbMCwxMzMsMjY3LDQwMCw1MzMsNjY3LDgwMCw5MzMsMTA2NywxMjAwLDEzMzMsMTQ2NywxNjAwLDE3MzMsMTg2NywyMDAwLDIxMzMsMjI2NywyNDAwLDI1MzMsMjY2NywyODAwLDI5MzMsMzA2NywzMjAwLDMzMzMsMzQ2NywzNjAwLDM3MzMsMzg2Nyw0MDAwLDQxMzMsNDI2Nyw0NDAwLDQ1MzMsNDY2Nyw0ODAwLDQ5MzMsNTA2Nyw1MjAwLDUzMzMsNTQ2Nyw1NjAwLDU3MzMsNTg2Nyw2MDAwLDYxMzMsNjI2Nyw2NDAwLDY1MzMsNjY2Nyw2ODAwLDY5MzMsNzA2Nyw3MjAwLDczMzMsNzQ2Nyw3NjAwLDc3MzMsNzg2Nyw4MDAwLDgxMzMsODI2Nyw4NDAwLDg1MzMsODY2Nyw4ODAwLDg5MzMsOTA2Nyw5MDc1XSwidHJhY2siOnsiZGF5IjoiMjAyNi0wMS0wMSIsImNvdXJzZSI6IjI5ZTlmYzNiIiwiZ2VuIjoyfX0',
  benchmark:
    'eyJ2IjozLCJ0IjoxNTQ4OCwicCI6W1swLDYsMCwwXSxbMCw2LDIuNSwwXSxbMCw2LDcsMF0sWzAsNiwxMywwXSxbMCw2LDIxLjUsMF0sWzAsNiwzMS41LDBdLFswLDYsNDQsMF0sWzAsNiw1OCwwXSxbMCw2LDc0LDBdLFswLDYsOTIuNSwwXSxbMCw2LDExMSwwLjAxXSxbMCw2LDEyOS41LDAuMDNdLFswLjUsNiwxNDcuNSwwLjA4XSxbMS41LDYsMTY1LDAuMTZdLFszLjUsNiwxODEuNSwwLjI1XSxbNi41LDYsMTk3LDAuMzZdLFsxMC41LDYsMjExLjUsMC40N10sWzE2LDYsMjI1LjUsMC41OV0sWzIzLDYsMjM4LjUsMC43M10sWzMyLDYuNSwyNTEsMC45XSxbNDIuNSw3LDI2MiwxLjA4XSxbNTQuNSw3LDI3MSwxLjI3XSxbNjguNSw3LjUsMjc4LDEuNDVdLFs4Myw3LjUsMjgyLjUsMS41OV0sWzk4LDcuNSwyODQuNSwxLjcyXSxbMTEzLjUsNy41LDI4NC41LDEuODFdLFsxMjguNSw3LDI4Mi41LDEuODldLFsxNDMsNywyNzkuNSwxLjkzXSxbMTU3LjUsNywyNzUsMi4wOF0sWzE3MS41LDYuNSwyNjkuNSwyLjE3XSxbMTg1LDYuNSwyNjIsMi4wOV0sWzIwMC41LDYuNSwyNTQsMi4wMV0sWzIxNyw3LDI0NS41LDEuOF0sWzIzNSw3LjUsMjM4LjUsMS42NF0sWzI1NC41LDgsMjMzLjUsMS40Nl0sWzI3My41LDguNSwyMzIsMS4zNF0sWzI5MSw5LDIzMiwxLjI5XSxbMzA2LjUsOSwyMzQsMS4yMl0sWzMyMS41LDksMjM3LjUsMS4wN10sWzMzNS41LDksMjQyLjUsMC44NV0sWzM0OSw5LDI1MCwwLjYyXSxbMzYwLDksMjYwLDAuNDNdLFszNjksOSwyNzEuNSwwLjI4XSxbMzc2LDguNSwyODQuNSwwLjE2XSxbMzgxLDguNSwyOTguNSwwLjA2XSxbMzg0LjUsOC41LDMxMywtMC4wMl0sWzM4Ni41LDguNSwzMjgsLTAuMDhdLFszODYuNSw4LjUsMzQzLC0wLjE0XSxbMzg2LDEwLDM1OCwtMC4yXSxbMzg0LjUsMTEuNSwzNzIuNSwtMC4yMl0sWzM4MywxMiwzODcuNSwtMC4yM10sWzM4MSwxMiw0MDIsLTAuMjJdLFszNzkuNSwxMS41LDQxNywtMC4yMV0sWzM3Ny41LDEwLjUsNDMxLjUsLTAuMl0sWzM3NS41LDEwLjUsNDQ2LjUsLTAuMThdLFszNzMsMTEsNDYxLC0wLjE1XSxbMzcxLDExLDQ3NiwtMC4xM10sWzM2OC41LDExLDQ5MC41LC0wLjExXSxbMzY3LDExLDUwNSwtMC4xXSxbMzY1LDEwLjUsNTIwLC0wLjA4XSxbMzY0LDEwLjUsNTM1LC0wLjA1XSxbMzYyLjUsMTAuNSw1NDkuNSwtMC4wMV0sWzM2MiwxMCw1NjQuNSwwLjA1XSxbMzYyLjUsMTAsNTc5LjUsMC4xMV0sWzM2MywxMCw1OTQsMC4xOF0sWzM2NSwxMC41LDYwOSwwLjI2XSxbMzY4LDEwLjUsNjIzLjUsMC4zNF0sWzM3MiwxMSw2MzgsMC40Ml0sWzM3NywxMS41LDY1MiwwLjQ5XSxbMzgzLDExLjUsNjY2LDAuNTVdLFszODkuNSwxMiw2NzksMC41OV0sWzM5Ny41LDEyLjUsNjkyLDAuNjJdLFs0MDcsMTIuNSw3MDYuNSwwLjYzXSxbNDE4LDEyLjUsNzIxLjUsMC42Ml0sWzQyOC41LDEyLjUsNzM2LjUsMC41N10sWzQzOC41LDEyLjUsNzUxLjUsMC40Nl0sWzQ0NywxMi41LDc2Ni41LDAuMzFdLFs0NTMuNSwxMiw3ODEsMC4xOV0sWzQ1OCwxMS41LDc5NCwwLjA4XSxbNDYyLDEyLDgwNSwtMC4wNl0sWzQ2MywxMiw4MTYuNSwtMC4yNV0sWzQ2MS41LDEyLDgyOC41LC0wLjQ5XSxbNDU3LjUsMTIsODQwLjUsLTAuNzJdLFs0NTAuNSwxMi41LDg1MiwtMC44OV0sWzQ0MS41LDEzLDg2Mi41LC0wLjk4XSxbNDMwLDEzLDg3MiwtMS4wNF0sWzQxNS41LDEzLjUsODgxLC0xLjFdLFszOTksMTQsODkwLC0xLjE0XSxbMzgyLDE0LjUsODk4LC0xLjE3XSxbMzY1LDE0LjUsOTA1LjUsLTEuMThdLFszNDgsMTQuNSw5MTMsLTEuMThdLFszMzAuNSwxNC41LDkyMCwtMS4xNl0sWzMxNCwxNCw5MjcsLTEuMTRdLFsyOTcuNSwxNCw5MzQuNSwtMS4wOV0sWzI4MiwxNCw5NDIuNSwtMS4wM10sWzI2Ny41LDEzLjUsOTUwLC0wLjk3XSxbMjU0LDEyLjUsOTU4LjUsLTAuOTFdLFsyNDIsMTIsOTY3LC0wLjg3XSxbMjI5LDExLjUsOTc3LjUsLTAuNjZdLFsyMTguNSwxMSw5ODgsLTAuNV0sWzIwOS41LDEwLDEwMDAuNSwtMC40NF0sWzIwMiw5LjUsMTAxMywtMC40N10sWzE5NSw4LjUsMTAyNiwtMC41NV0sWzE4Ny41LDgsMTAzOSwtMC41OF0sWzE3OS41LDcuNSwxMDUxLjUsLTAuNTVdLFsxNzIsNy41LDEwNjQuNSwtMC41XSxbMTY0LjUsNywxMDc3LjUsLTAuNDVdLFsxNTcuNSw3LDEwOTAuNSwtMC40Ml0sWzE1MSw3LDExMDMuNSwtMC40Ml0sWzE0NC41LDcsMTExNywtMC40M10sWzEzOC41LDcsMTEzMC41LC0wLjQzXSxbMTMyLDcsMTE0NCwtMC40Ml0sWzEyNiw3LDExNTcuNSwtMC40XSxbMTIwLDcsMTE3MSwtMC4zOV0sWzExNC41LDcsMTE4NC41LC0wLjM5XSxbMTA4LjUsNywxMTk4LjUsLTAuMzhdLFsxMDMsNywxMjEyLC0wLjM2XSxbMTAyLDcsMTIxNCwtMC4zNV1dLCJ0cyI6WzAsMTMzLDI2Nyw0MDAsNTMzLDY2Nyw4MDAsOTMzLDEwNjcsMTIwMCwxMzMzLDE0NjcsMTYwMCwxNzMzLDE4NjcsMjAwMCwyMTMzLDIyNjcsMjQwMCwyNTMzLDI2NjcsMjgwMCwyOTMzLDMwNjcsMzIwMCwzMzMzLDM0NjcsMzYwMCwzNzMzLDM4NjcsNDAwMCw0MTMzLDQyNjcsNDQwMCw0NTMzLDQ2NjcsNDgwMCw0OTMzLDUwNjcsNTIwMCw1MzMzLDU0NjcsNTYwMCw1NzMzLDU4NjcsNjAwMCw2MTMzLDYyNjcsNjQwMCw2NTMzLDY2NjcsNjgwMCw2OTMzLDcwNjcsNzIwMCw3MzMzLDc0NjcsNzYwMCw3NzMzLDc4NjcsODAwMCw4MTMzLDgyNjcsODQwMCw4NTMzLDg2NjcsODgwMCw4OTMzLDkwNjcsOTIwMCw5MzMzLDk0NjcsOTYwMCw5NzMzLDk4NjcsMTAwMDAsMTAxMzMsMTAyNjcsMTA0MDAsMTA1MzMsMTA2NjcsMTA4MDAsMTA5MzMsMTEwNjcsMTEyMDAsMTEzMzMsMTE0NjcsMTE2MDAsMTE3MzMsMTE4NjcsMTIwMDAsMTIxMzMsMTIyNjcsMTI0MDAsMTI1MzMsMTI2NjcsMTI4MDAsMTI5MzMsMTMwNjcsMTMyMDAsMTMzMzMsMTM0NjcsMTM2MDAsMTM3MzMsMTM4NjcsMTQwMDAsMTQxMzMsMTQyNjcsMTQ0MDAsMTQ1MzMsMTQ2NjcsMTQ4MDAsMTQ5MzMsMTUwNjcsMTUyMDAsMTUzMzMsMTU0NjcsMTU0ODhdLCJ0cmFjayI6eyJkYXkiOiIyMDI2LTAxLTAyIiwiY291cnNlIjoiMWVjYzEzMjMiLCJnZW4iOjJ9fQ',
};

/** Fixed-course identity days (daily keeps the requested day). */
export const FIXED_IDENTITY_DAYS: Record<'practice' | 'benchmark', string> = {
  practice: '2026-01-01',
  benchmark: '2026-01-02',
};

/** Recorded exact finish times (ms) of the reference runs, for documentation. */
export const REFERENCE_TIMES_MS: Record<'practice' | 'benchmark', number> = {
  practice: 9075,
  benchmark: 15488,
};

/**
 * Medal margins over the recorded reference time. Gold is deliberately slower
 * than the reference (which was a clean skilled run), so gold is attainable
 * while the REFERENCE stays the pace to chase.
 */
export const FIXED_TARGET_MARGINS = { gold: 1.08, silver: 1.2, bronze: 1.36 } as const;

/**
 * Daily medal factors over `estimateCleanTime`. Calibrated offline against 22
 * representative daily seeds driven by the skilled controller: clean-run
 * time/estimate ratios were 1.031-1.054 (median 1.045). Gold at 1.10 keeps a
 * ~5% margin over that measured clean pace; silver/bronze step out for a wider
 * player base.
 */
export const DAILY_TARGET_FACTORS = { gold: 1.1, silver: 1.22, bronze: 1.4 } as const;

export const COURSE_IDENTITY_GEN = TRACK_IDENTITY_GEN;
