// course-reference.ts — recorded reference runs for the fixed courses.
//
// These are NOT human records and NOT invented targets. Each payload is an
// actual clean simulated completion (0 respawns, 0 wall contacts) of the exact
// authored course, captured with the skilled controller and encoded by the
// shared ghost codec with a packed course identity. `reference` is surfaced to
// the UI as REFERENCE, never as a best/human/world record.
//
// Provenance (deterministic, reproducible by the courses test): course-retune
// recordings on the current physics (ACCEL_ROAD 85 + ACCEL_BOOST_MAKEUP 55 +
// LAUNCH_RAMP_MIN 0.35 rising to full by LAUNCH_RAMP_END 60, cruise 140 /
// drift 112, gated rail clamp, road-relative dirt, gate-free ground station).
// Each payload is the exact skilled-controller run the C5 check replays
// (0 walls, 0 respawns).
//   practice  (2026-01-01) clean informed run, 9540 ms, tag practice.
//   benchmark (2026-01-02) clean informed run, 16089 ms, tag benchmark.
// Re-recorded 2026-09-18 (sink2): the decisive launch softening retimed the
// skilled runs (+366/+417 ms, launch + slow-corner pull); geometry checksums
// unchanged (practice 29e9fc3b, benchmark 1ecc1323).
// The encoded payload carries { day, courseChecksum, gen }; course.ts checks it
// against the freshly built geometry before handing it out.
import { TRACK_IDENTITY_GEN } from './ghost.js';

// Bumped for the speed-dirt pass: geometry, physics pace and competition
// identity changed, so medal margins and reference recordings must be
// re-derived. See docs/agents/speed-dirt-courses.md.
export const COURSE_REFERENCE_VERSION = 2;

/**
 * Encoding budget for the bundled reference demos. These are shipped locally
 * with the build, not share URLs, so they are encoded at effectively unlimited
 * budget to keep EVERY 120 ms recorded sample. Using the share-URL budget
 * (GHOST_URL_BUDGET) strides the demo roughly 1s apart and interpolation then
 * cuts up to ~3u through inside curbs; the full payloads stay under the codec's
 * 8192-char decode limit and interpolate within the 0.5u quantization bound.
 */
export const REFERENCE_ENCODE_BUDGET = 1 << 30;

/** Encoded GhostRec payloads (base64url, versioned codec with course identity). */
export const REFERENCE_ENCODED: Record<'practice' | 'benchmark', string> = {
  practice:
    'eyJ2IjozLCJ0Ijo5NTQwLCJwIjpbWzAsNiwwLDBdLFswLDYsMS41LDBdLFswLDYsNC41LDBdLFswLDYsNy41LDBdLFswLDYsMTIsMF0sWzAsNiwxNy41LDBdLFswLDYsMjQuNSwwXSxbMCw2LDMyLjUsMF0sWzAsNiw0Mi41LDBdLFswLDYsNTMuNSwwXSxbMCw2LDY2LjUsMF0sWzAsNiw4MC41LDBdLFswLDYsOTYuNSwwXSxbMCw2LDExNCwtMC4wMV0sWy0wLjUsNiwxMzEuNSwtMC4wNl0sWy0xLDYsMTQ4LjUsLTAuMTRdLFstMi41LDYsMTY1LC0wLjI0XSxbLTUsNiwxODAuNSwtMC4zNF0sWy05LDYsMTk1LC0wLjQ3XSxbLTE0LjUsNiwyMDksLTAuNl0sWy0yMS41LDYsMjIyLC0wLjc2XSxbLTMwLjUsNiwyMzQuNSwtMC45Nl0sWy00Miw2LjUsMjQ1LC0xLjE3XSxbLTU0LjUsNywyNTMuNSwtMS4zNV0sWy02OSw3LjUsMjU5LC0xLjUxXSxbLTgzLjUsOCwyNjIuNSwtMS42M10sWy05OSw4LDI2NCwtMS43M10sWy0xMTQsOC41LDI2My41LC0xLjc5XSxbLTEyOC41LDguNSwyNjEuNSwtMS44M10sWy0xNDUsOC41LDI1Ny41LC0xLjk4XSxbLTE2MSw4LjUsMjUyLjUsLTIuMDVdLFstMTc3LDguNSwyNDYsLTEuOTddLFstMTk0LDguNSwyMzksLTEuOTFdLFstMjEyLjUsOC41LDIzMiwtMS43Ml0sWy0yMzIuNSw5LDIyNiwtMS41OF0sWy0yNTQsOS41LDIyMi41LC0xLjQyXSxbLTI3NC41LDEwLjUsMjIyLC0xLjMyXSxbLTI5MywxMSwyMjMuNSwtMS4yOV0sWy0zMDkuNSwxMS41LDIyNiwtMS4yNF0sWy0zMjUsMTIsMjI5LjUsLTEuMTJdLFstMzM5LDEyLjUsMjM0LjUsLTAuOTFdLFstMzUyLDEyLjUsMjQxLC0wLjY3XSxbLTM2My41LDEyLjUsMjUwLC0wLjQ3XSxbLTM3Mi41LDEyLjUsMjYwLjUsLTAuMzJdLFstMzc5LjUsMTIuNSwyNzEuNSwtMC4yXSxbLTM4NC41LDEyLjUsMjg0LC0wLjA5XSxbLTM4OCwxMi41LDI5Ni41LC0wLjAxXSxbLTM5MCwxMi41LDMxMCwwLjA1XSxbLTM5MC41LDEyLjUsMzIzLjUsMC4xXSxbLTM5MC41LDEzLDMzNywwLjE1XSxbLTM4OS41LDEzLjUsMzUxLDAuMThdLFstMzg4LDEzLjUsMzY1LDAuMThdLFstMzg2LDE0LjUsMzc5LDAuMTddLFstMzg0LDE0LjUsMzkzLjUsMC4xNl0sWy0zODIsMTQuNSw0MDcuNSwwLjE0XSxbLTM4MCwxNCw0MjEuNSwwLjExXSxbLTM3OCwxMyw0MzYsMC4wOF0sWy0zNzYsMTEuNSw0NTAsMC4wNF0sWy0zNzQuNSwxMSw0NjYsLTAuMDJdLFstMzc0LjUsMTAsNDgzLC0wLjE0XSxbLTM3Ni41LDksNTAyLC0wLjI5XSxbLTM4MSw4LDUyMS41LC0wLjQyXSxbLTM4Ny41LDcuNSw1NDIsLTAuNTJdLFstMzk2LDcsNTYxLC0wLjU5XSxbLTQwNS41LDcsNTc4LC0wLjYxXSxbLTQxNS41LDcsNTk0LC0wLjY0XSxbLTQyNi41LDcsNjA5LC0wLjY3XSxbLTQzOCw3LDYyNCwtMC43XSxbLTQ0OS41LDcsNjM4LjUsLTAuNzJdLFstNDYyLDcsNjUyLjUsLTAuNzNdLFstNDc0LjUsNyw2NjYuNSwtMC43NV0sWy00ODcsNyw2ODAsLTAuNzddLFstNDk0LDcsNjg3LjUsLTAuOF1dLCJ0cyI6WzAsMTMzLDI2Nyw0MDAsNTMzLDY2Nyw4MDAsOTMzLDEwNjcsMTIwMCwxMzMzLDE0NjcsMTYwMCwxNzMzLDE4NjcsMjAwMCwyMTMzLDIyNjcsMjQwMCwyNTMzLDI2NjcsMjgwMCwyOTMzLDMwNjcsMzIwMCwzMzMzLDM0NjcsMzYwMCwzNzMzLDM4NjcsNDAwMCw0MTMzLDQyNjcsNDQwMCw0NTMzLDQ2NjcsNDgwMCw0OTMzLDUwNjcsNTIwMCw1MzMzLDU0NjcsNTYwMCw1NzMzLDU4NjcsNjAwMCw2MTMzLDYyNjcsNjQwMCw2NTMzLDY2NjcsNjgwMCw2OTMzLDcwNjcsNzIwMCw3MzMzLDc0NjcsNzYwMCw3NzMzLDc4NjcsODAwMCw4MTMzLDgyNjcsODQwMCw4NTMzLDg2NjcsODgwMCw4OTMzLDkwNjcsOTIwMCw5MzMzLDk0NjcsOTU0MF0sInRyYWNrIjp7ImRheSI6IjIwMjYtMDEtMDEiLCJjb3Vyc2UiOiIyOWU5ZmMzYiIsImdlbiI6Mn19',
  benchmark:
    'eyJ2IjozLCJ0IjoxNjA4OSwicCI6W1swLDYsMCwwXSxbMCw2LDEuNSwwXSxbMCw2LDQuNSwwXSxbMCw2LDcuNSwwXSxbMCw2LDEyLDBdLFswLDYsMTcuNSwwXSxbMCw2LDI0LjUsMF0sWzAsNiwzMi41LDBdLFswLDYsNDIuNSwwXSxbMCw2LDUzLjUsMF0sWzAsNiw2Ni41LDBdLFswLDYsODAuNSwwXSxbMCw2LDk2LjUsMF0sWzAsNiwxMTQsMF0sWzAsNiwxMzIsMC4wM10sWzAuNSw2LDE1MCwwLjA4XSxbMS41LDYsMTY3LDAuMTddLFszLjUsNiwxODMuNSwwLjI2XSxbNi41LDYsMTk4LjUsMC4zN10sWzExLDYsMjEzLDAuNDldLFsxNi41LDYsMjI3LDAuNjFdLFsyNCw2LDI0MCwwLjc1XSxbMzMsNi41LDI1Mi41LDAuOTJdLFs0My41LDcsMjYzLDEuMTFdLFs1Niw3LDI3MiwxLjI5XSxbNzAsNy41LDI3OC41LDEuNDZdLFs4NSw3LjUsMjgyLjUsMS42XSxbMTAwLDcuNSwyODQuNSwxLjczXSxbMTE1LDcuNSwyODQuNSwxLjgyXSxbMTMwLDcsMjgyLjUsMS45XSxbMTQ0LjUsNywyNzksMS45NF0sWzE1OSw3LDI3NC41LDIuMDldLFsxNzMsNi41LDI2OC41LDIuMTVdLFsxODcsNi41LDI2MSwyLjA4XSxbMjAyLDcsMjUzLDJdLFsyMTksNywyNDUsMS43OF0sWzIzNyw3LjUsMjM3LjUsMS42Ml0sWzI1Ni41LDgsMjMzLjUsMS40NV0sWzI3NS41LDguNSwyMzIsMS4zNF0sWzI5Myw5LDIzMi41LDEuMjldLFszMDguNSw5LDIzNC41LDEuMjFdLFszMjMsOSwyMzgsMS4wNV0sWzMzNyw5LDI0MywwLjgzXSxbMzQ5LjUsOSwyNTAuNSwwLjYyXSxbMzYwLDksMjU5LjUsMC40NF0sWzM2OC41LDksMjcwLDAuM10sWzM3NC41LDguNSwyODEuNSwwLjE4XSxbMzc5LjUsOC41LDI5My41LDAuMDldLFszODIuNSw4LjUsMzA2LjUsMC4wMV0sWzM4NC41LDguNSwzMTkuNSwtMC4wNl0sWzM4NSw4LjUsMzMzLC0wLjFdLFszODUsOSwzNDYuNSwtMC4xNF0sWzM4NCwxMC41LDM2MC41LC0wLjE2XSxbMzgyLjUsMTIsMzc0LjUsLTAuMTddLFszODEsMTIuNSwzODguNSwtMC4xN10sWzM3OS41LDEyLjUsNDAyLjUsLTAuMTddLFszNzgsMTEuNSw0MTYuNSwtMC4xNl0sWzM3Ni41LDEwLjUsNDMwLjUsLTAuMTVdLFszNzUsMTAuNSw0NDQuNSwtMC4xNV0sWzM3MywxMSw0NTksLTAuMTNdLFszNzEsMTEsNDc0LC0wLjEyXSxbMzY5LDExLDQ4OC41LC0wLjExXSxbMzY3LjUsMTEsNTAzLjUsLTAuMV0sWzM2NiwxMC41LDUxOCwtMC4wOF0sWzM2NC41LDEwLjUsNTMzLC0wLjA2XSxbMzYzLjUsMTAuNSw1NDcuNSwtMC4wMl0sWzM2Mi41LDEwLDU2Mi41LDAuMDNdLFszNjIuNSwxMCw1NzcuNSwwLjA5XSxbMzYzLjUsMTAsNTkyLjUsMC4xN10sWzM2NSwxMC41LDYwNywwLjI1XSxbMzY3LjUsMTAuNSw2MjIsMC4zM10sWzM3MS41LDExLDYzNiwwLjQxXSxbMzc2LjUsMTEuNSw2NTAuNSwwLjQ4XSxbMzgyLDExLjUsNjY0LDAuNTRdLFszODksMTIsNjc3LjUsMC41OV0sWzM5Ni41LDEyLjUsNjkwLjUsMC42Ml0sWzQwNiwxMi41LDcwNC41LDAuNjNdLFs0MTYuNSwxMi41LDcxOS41LDAuNjJdLFs0MjcuNSwxMi41LDczNC41LDAuNThdLFs0MzcuNSwxMi41LDc0OS41LDAuNDhdLFs0NDYsMTIuNSw3NjQuNSwwLjMzXSxbNDUyLjUsMTIsNzc5LjUsMC4yMV0sWzQ1Ny41LDEyLDc5Mi41LDAuMV0sWzQ2MS41LDEyLDgwMy41LC0wLjA0XSxbNDYzLDEyLDgxNC41LC0wLjIyXSxbNDYyLDEyLDgyNiwtMC40NV0sWzQ1OSwxMiw4MzcuNSwtMC42OF0sWzQ1MywxMi41LDg0OCwtMC44NV0sWzQ0NS41LDEyLjUsODU3LjUsLTAuOTZdLFs0MzYsMTMsODY2LjUsLTEuMDJdLFs0MjQsMTMuNSw4NzQuNSwtMS4wN10sWzQwOSwxNCw4ODMsLTEuMV0sWzM5Mi41LDE0LDg5MiwtMS4xM10sWzM3NiwxNC41LDkwMCwtMS4xNV0sWzM1OSwxNC41LDkwNy41LC0xLjE2XSxbMzQyLDE0LjUsOTE1LjUsLTEuMTVdLFszMjQuNSwxNCw5MjMsLTEuMTRdLFszMDgsMTQsOTMwLjUsLTEuMTJdLFsyOTIsMTQsOTM4LjUsLTEuMDhdLFsyNzYuNSwxMy41LDk0Ni41LC0xLjAyXSxbMjYyLjUsMTMsOTU0LjUsLTAuOTVdLFsyNDksMTIuNSw5NjMsLTAuOV0sWzIzNywxMiw5NzIsLTAuODVdLFsyMjQuNSwxMSw5ODIuNSwtMC42NF0sWzIxMy41LDEwLjUsOTkzLjUsLTAuNDhdLFsyMDUsMTAsMTAwNiwtMC40MV0sWzE5OCw5LDEwMTksLTAuNDVdLFsxOTEsOCwxMDMyLjUsLTAuNTJdLFsxODQsNy41LDEwNDUuNSwtMC41Nl0sWzE3Ni41LDcuNSwxMDU4LC0wLjU0XSxbMTY5LDcsMTA3MSwtMC40OV0sWzE2MS41LDcsMTA4NCwtMC40NF0sWzE1NSw3LDEwOTcsLTAuNDJdLFsxNDguNSw3LDExMTAuNSwtMC40Ml0sWzE0Miw3LDExMjQsLTAuNDNdLFsxMzYsNywxMTM3LjUsLTAuNDNdLFsxMjkuNSw3LDExNTEsLTAuNDJdLFsxMjMuNSw3LDExNjQuNSwtMC40MV0sWzExNy41LDcsMTE3OCwtMC40XSxbMTExLjUsNywxMTkxLjUsLTAuMzldLFsxMDYsNywxMjA1LC0wLjM4XSxbMTAyLDcsMTIxNCwtMC4zNV1dLCJ0cyI6WzAsMTMzLDI2Nyw0MDAsNTMzLDY2Nyw4MDAsOTMzLDEwNjcsMTIwMCwxMzMzLDE0NjcsMTYwMCwxNzMzLDE4NjcsMjAwMCwyMTMzLDIyNjcsMjQwMCwyNTMzLDI2NjcsMjgwMCwyOTMzLDMwNjcsMzIwMCwzMzMzLDM0NjcsMzYwMCwzNzMzLDM4NjcsNDAwMCw0MTMzLDQyNjcsNDQwMCw0NTMzLDQ2NjcsNDgwMCw0OTMzLDUwNjcsNTIwMCw1MzMzLDU0NjcsNTYwMCw1NzMzLDU4NjcsNjAwMCw2MTMzLDYyNjcsNjQwMCw2NTMzLDY2NjcsNjgwMCw2OTMzLDcwNjcsNzIwMCw3MzMzLDc0NjcsNzYwMCw3NzMzLDc4NjcsODAwMCw4MTMzLDgyNjcsODQwMCw4NTMzLDg2NjcsODgwMCw4OTMzLDkwNjcsOTIwMCw5MzMzLDk0NjcsOTYwMCw5NzMzLDk4NjcsMTAwMDAsMTAxMzMsMTAyNjcsMTA0MDAsMTA1MzMsMTA2NjcsMTA4MDAsMTA5MzMsMTEwNjcsMTEyMDAsMTEzMzMsMTE0NjcsMTE2MDAsMTE3MzMsMTE4NjcsMTIwMDAsMTIxMzMsMTIyNjcsMTI0MDAsMTI1MzMsMTI2NjcsMTI4MDAsMTI5MzMsMTMwNjcsMTMyMDAsMTMzMzMsMTM0NjcsMTM2MDAsMTM3MzMsMTM4NjcsMTQwMDAsMTQxMzMsMTQyNjcsMTQ0MDAsMTQ1MzMsMTQ2NjcsMTQ4MDAsMTQ5MzMsMTUwNjcsMTUyMDAsMTUzMzMsMTU0NjcsMTU2MDAsMTU3MzMsMTU4NjcsMTYwMDAsMTYwODldLCJ0cmFjayI6eyJkYXkiOiIyMDI2LTAxLTAyIiwiY291cnNlIjoiMWVjYzEzMjMiLCJnZW4iOjJ9fQ',
};

/** Fixed-course identity days (daily keeps the requested day). */
export const FIXED_IDENTITY_DAYS: Record<'practice' | 'benchmark', string> = {
  practice: '2026-01-01',
  benchmark: '2026-01-02',
};

/** Recorded exact finish times (ms) of the reference runs, for documentation. */
export const REFERENCE_TIMES_MS: Record<'practice' | 'benchmark', number> = {
  practice: 9540,
  benchmark: 16089,
};

/**
 * Medal margins over the recorded reference time. Gold is deliberately slower
 * than the reference (which was a clean skilled run), so gold is attainable
 * while the REFERENCE stays the pace to chase.
 */
export const FIXED_TARGET_MARGINS = { gold: 1.08, silver: 1.2, bronze: 1.36 } as const;

/**
 * Daily medal factors over `estimateCleanTime`. Calibrated offline against 22
 * representative daily seeds driven by the skilled controller: clean-run
 * time/estimate ratios were 1.031-1.054 (median 1.045). Gold at 1.10 keeps a
 * ~5% margin over that measured clean pace; silver/bronze step out for a wider
 * player base.
 */
export const DAILY_TARGET_FACTORS = { gold: 1.1, silver: 1.22, bronze: 1.4 } as const;

export const COURSE_IDENTITY_GEN = TRACK_IDENTITY_GEN;
